-- AlterTable
ALTER TABLE `Period` ADD COLUMN `maximum_seat` INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN `reserved_seat` INTEGER NOT NULL DEFAULT 10;

-- AlterTable
ALTER TABLE `Ticket` ADD COLUMN `duration` VARCHAR(191) NOT NULL DEFAULT '30 min',
    ADD COLUMN `fare` INTEGER NOT NULL DEFAULT 150,
    ADD COLUMN `identnumber` VARCHAR(191) NOT NULL DEFAULT '12AC1234',
    ADD COLUMN `note` VARCHAR(191) NOT NULL DEFAULT '';
